name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy kivy_deps pillow pyinstaller

    - name: Build with PyInstaller
      env:
        KIVY_WINDOW: mock
        KIVY_GL_BACKEND: mock
        KIVY_NO_ARGS: "1"
        KIVY_NO_CONSOLELOG: "1"
      run: pyinstaller monika.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cool
        path: dist/cool/
