name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Kivy works best with 3.11 or 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy pillow pyinstaller

    - name: Build with PyInstaller
      run: pyinstaller monika.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: coolapp
        path: dist/cool/
